name: open_meteo
description: An simple, fast, asynchronous Dart/Flutter client package for OpenMeteo API 
version: 0.0.9
homepage: https://github.com/Neurs12/open-meteo-dart

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
